### ISSUE TITLE
don't keep regenerating the IPV public key

### ISSUE THREAD

**Issue by pauldougan** [zapthedingbat/gov-uk-one-login-sim#9]
when the simulator starts it will generate a new IPV key

this should be initialised if one does not exist otherwise it should be stable over restarts of the simulator and reboots of the hardware

**Comment by zapthedingbat** [comment]
I've got this working now. If you run the docker container the first time it will generate a key and write it to `/app/config/keys`. This is a docker volume so it should be persisted across restarts. You can mount this directory externally too if needed.
